// The --vscode-* values a VS Code webview is given, per built-in theme, for
// every token the merge webview reads (packages/webview-ui/src: diff.css,
// shell.css, tokens.css, hostTokens.ts, theme.ts …). VS Code injects these on
// <html>/<body> of every webview; a headless render that supplies only three of
// them (the unit tests' page) paints the chrome from fallbacks no user sees.
//
// Values are VS Code's defaults for "Dark+ (default dark)", "Light+ (default
// light)", "Dark High Contrast" and "Light High Contrast" (the colorRegistry
// defaults plus the themes' own overrides). A token a theme leaves undefined is
// left out here too, so a `var(--x, fallback)` behaves as it does in VS Code.

export type VsCodeTheme = "dark" | "light" | "hc-dark" | "hc-light";

export const VSCODE_THEME_NAMES: Record<VsCodeTheme, string> = {
  dark: "Dark+",
  light: "Light+",
  "hc-dark": "Dark High Contrast",
  "hc-light": "Light High Contrast",
};

/** The body classes VS Code sets on a webview for each theme kind. */
export const BODY_CLASS: Record<VsCodeTheme, string> = {
  dark: "vscode-dark",
  light: "vscode-light",
  "hc-dark": "vscode-high-contrast",
  "hc-light": "vscode-high-contrast vscode-high-contrast-light",
};

const FONT = {
  "--vscode-font-family": `-apple-system, BlinkMacSystemFont, sans-serif`,
  "--vscode-font-size": "13px",
  "--vscode-font-weight": "normal",
  "--vscode-editor-font-family": `Menlo, Monaco, "Courier New", monospace`,
  "--vscode-editor-font-size": "12px",
  "--vscode-editor-font-weight": "normal",
};

export const VSCODE_THEMES: Record<VsCodeTheme, Record<string, string>> = {
  dark: {
    ...FONT,
    "--vscode-foreground": "#cccccc",
    "--vscode-descriptionForeground": "#ccccccb3",
    "--vscode-errorForeground": "#f48771",
    "--vscode-focusBorder": "#007fd4",
    "--vscode-widget-shadow": "rgba(0, 0, 0, 0.36)",
    "--vscode-icon-foreground": "#c5c5c5",
    "--vscode-textLink-foreground": "#3794ff",
    "--vscode-badge-background": "#4d4d4d",
    "--vscode-badge-foreground": "#ffffff",
    "--vscode-button-background": "#0e639c",
    "--vscode-button-foreground": "#ffffff",
    "--vscode-button-hoverBackground": "#1177bb",
    "--vscode-button-secondaryBackground": "#3a3d41",
    "--vscode-button-secondaryForeground": "#ffffff",
    "--vscode-button-secondaryHoverBackground": "#45494e",
    "--vscode-charts-blue": "#3794ff",
    "--vscode-charts-green": "#89d185",
    "--vscode-charts-purple": "#b180d7",
    "--vscode-charts-red": "#f14c4c",
    "--vscode-charts-yellow": "#cca700",
    "--vscode-checkbox-background": "#3c3c3c",
    "--vscode-checkbox-border": "#6b6b6b",
    "--vscode-dropdown-background": "#3c3c3c",
    "--vscode-dropdown-border": "#3c3c3c",
    "--vscode-dropdown-foreground": "#f0f0f0",
    "--vscode-editor-background": "#1e1e1e",
    "--vscode-editor-foreground": "#d4d4d4",
    "--vscode-editor-inactiveSelectionBackground": "#3a3d41",
    "--vscode-editor-selectionBackground": "#264f78",
    "--vscode-editor-selectionHighlightBackground": "rgba(173, 214, 255, 0.15)",
    "--vscode-editorCursor-foreground": "#aeafad",
    "--vscode-editorGroupHeader-tabsBackground": "#252526",
    "--vscode-editorIndentGuide-background": "#404040",
    "--vscode-editorLineNumber-foreground": "#858585",
    "--vscode-editorLineNumber-activeForeground": "#c6c6c6",
    "--vscode-editorWarning-foreground": "#cca700",
    "--vscode-editorWidget-background": "#252526",
    "--vscode-editorWidget-border": "#454545",
    "--vscode-editorWidget-foreground": "#cccccc",
    "--vscode-gitDecoration-conflictingResourceForeground": "#e4676b",
    "--vscode-gitDecoration-ignoredResourceForeground": "#8c8c8c",
    "--vscode-gitDecoration-modifiedResourceForeground": "#e2c08d",
    "--vscode-gitDecoration-untrackedResourceForeground": "#73c991",
    "--vscode-inputOption-activeBackground": "rgba(0, 127, 212, 0.4)",
    "--vscode-inputOption-activeBorder": "rgba(0, 122, 204, 0)",
    "--vscode-inputOption-activeForeground": "#ffffff",
    "--vscode-list-activeSelectionBackground": "#04395e",
    "--vscode-list-activeSelectionForeground": "#ffffff",
    "--vscode-list-hoverBackground": "#2a2d2e",
    "--vscode-panel-border": "rgba(128, 128, 128, 0.35)",
    "--vscode-scrollbarSlider-background": "rgba(121, 121, 121, 0.4)",
    "--vscode-scrollbarSlider-hoverBackground": "rgba(100, 100, 100, 0.7)",
    "--vscode-scrollbarSlider-activeBackground": "rgba(191, 191, 191, 0.4)",
    "--vscode-sideBar-background": "#252526",
    "--vscode-statusBarItem-warningBackground": "#7a6400",
    "--vscode-statusBarItem-warningForeground": "#ffffff",
    "--vscode-toolbar-hoverBackground": "rgba(90, 93, 94, 0.31)",
  },
  light: {
    ...FONT,
    "--vscode-foreground": "#616161",
    "--vscode-descriptionForeground": "#717171",
    "--vscode-errorForeground": "#a1260d",
    "--vscode-focusBorder": "#0090f1",
    "--vscode-widget-shadow": "rgba(0, 0, 0, 0.16)",
    "--vscode-icon-foreground": "#424242",
    "--vscode-textLink-foreground": "#006ab1",
    "--vscode-badge-background": "#c4c4c4",
    "--vscode-badge-foreground": "#333333",
    "--vscode-button-background": "#007acc",
    "--vscode-button-foreground": "#ffffff",
    "--vscode-button-hoverBackground": "#0062a3",
    "--vscode-button-secondaryBackground": "#5f6a79",
    "--vscode-button-secondaryForeground": "#ffffff",
    "--vscode-button-secondaryHoverBackground": "#4c5561",
    "--vscode-charts-blue": "#1a85ff",
    "--vscode-charts-green": "#388a34",
    "--vscode-charts-purple": "#652d90",
    "--vscode-charts-red": "#e51400",
    "--vscode-charts-yellow": "#bf8803",
    "--vscode-checkbox-background": "#ffffff",
    "--vscode-checkbox-border": "#919191",
    "--vscode-dropdown-background": "#ffffff",
    "--vscode-dropdown-border": "#cecece",
    "--vscode-dropdown-foreground": "#616161",
    "--vscode-editor-background": "#ffffff",
    "--vscode-editor-foreground": "#000000",
    "--vscode-editor-inactiveSelectionBackground": "#e5ebf1",
    "--vscode-editor-selectionBackground": "#add6ff",
    "--vscode-editor-selectionHighlightBackground": "rgba(173, 214, 255, 0.5)",
    "--vscode-editorCursor-foreground": "#000000",
    "--vscode-editorGroupHeader-tabsBackground": "#f3f3f3",
    "--vscode-editorIndentGuide-background": "#d3d3d3",
    "--vscode-editorLineNumber-foreground": "#237893",
    "--vscode-editorLineNumber-activeForeground": "#0b216f",
    "--vscode-editorWarning-foreground": "#bf8803",
    "--vscode-editorWidget-background": "#f3f3f3",
    "--vscode-editorWidget-border": "#c8c8c8",
    "--vscode-editorWidget-foreground": "#616161",
    "--vscode-gitDecoration-conflictingResourceForeground": "#ad0707",
    "--vscode-gitDecoration-ignoredResourceForeground": "#8e8e90",
    "--vscode-gitDecoration-modifiedResourceForeground": "#895503",
    "--vscode-gitDecoration-untrackedResourceForeground": "#007100",
    "--vscode-inputOption-activeBackground": "rgba(0, 144, 241, 0.2)",
    "--vscode-inputOption-activeBorder": "rgba(0, 122, 204, 0)",
    "--vscode-inputOption-activeForeground": "#000000",
    "--vscode-list-activeSelectionBackground": "#0060c0",
    "--vscode-list-activeSelectionForeground": "#ffffff",
    "--vscode-list-hoverBackground": "#e8e8e8",
    "--vscode-panel-border": "rgba(128, 128, 128, 0.35)",
    "--vscode-scrollbarSlider-background": "rgba(100, 100, 100, 0.4)",
    "--vscode-scrollbarSlider-hoverBackground": "rgba(100, 100, 100, 0.7)",
    "--vscode-scrollbarSlider-activeBackground": "rgba(0, 0, 0, 0.6)",
    "--vscode-sideBar-background": "#f3f3f3",
    "--vscode-statusBarItem-warningBackground": "#725102",
    "--vscode-statusBarItem-warningForeground": "#ffffff",
    "--vscode-toolbar-hoverBackground": "rgba(184, 184, 184, 0.31)",
  },
  "hc-dark": {
    ...FONT,
    "--vscode-foreground": "#ffffff",
    "--vscode-descriptionForeground": "rgba(255, 255, 255, 0.7)",
    "--vscode-errorForeground": "#f48771",
    "--vscode-focusBorder": "#f38518",
    "--vscode-icon-foreground": "#ffffff",
    "--vscode-textLink-foreground": "#21a6ff",
    "--vscode-badge-background": "#000000",
    "--vscode-badge-foreground": "#ffffff",
    "--vscode-button-border": "#6fc3df",
    "--vscode-button-foreground": "#ffffff",
    "--vscode-button-secondaryForeground": "#ffffff",
    "--vscode-charts-blue": "#3794ff",
    "--vscode-charts-green": "#89d185",
    "--vscode-charts-purple": "#b180d7",
    "--vscode-charts-red": "#f14c4c",
    "--vscode-charts-yellow": "#cca700",
    "--vscode-checkbox-background": "#000000",
    "--vscode-checkbox-border": "#6fc3df",
    "--vscode-dropdown-background": "#000000",
    "--vscode-dropdown-border": "#6fc3df",
    "--vscode-dropdown-foreground": "#ffffff",
    "--vscode-editor-background": "#000000",
    "--vscode-editor-foreground": "#ffffff",
    "--vscode-editor-selectionBackground": "#ffffff",
    "--vscode-editorCursor-foreground": "#ffffff",
    "--vscode-editorIndentGuide-background": "#ffffff",
    "--vscode-editorLineNumber-foreground": "#ffffff",
    "--vscode-editorLineNumber-activeForeground": "#f38518",
    "--vscode-editorWarning-foreground": "#ffd370",
    "--vscode-editorWidget-background": "#0c141f",
    "--vscode-editorWidget-border": "#6fc3df",
    "--vscode-editorWidget-foreground": "#ffffff",
    "--vscode-gitDecoration-conflictingResourceForeground": "#c74e39",
    "--vscode-gitDecoration-ignoredResourceForeground": "#a7a7a7",
    "--vscode-gitDecoration-modifiedResourceForeground": "#e2c08d",
    "--vscode-gitDecoration-untrackedResourceForeground": "#73c991",
    "--vscode-inputOption-activeBorder": "#6fc3df",
    "--vscode-inputOption-activeForeground": "#ffffff",
    "--vscode-panel-border": "#6fc3df",
    "--vscode-scrollbarSlider-background": "rgba(111, 195, 223, 0.6)",
    "--vscode-scrollbarSlider-hoverBackground": "rgba(111, 195, 223, 0.8)",
    "--vscode-scrollbarSlider-activeBackground": "#6fc3df",
    "--vscode-sideBar-background": "#000000",
    "--vscode-statusBarItem-warningForeground": "#ffffff",
    "--vscode-widget-border": "#6fc3df",
  },
  "hc-light": {
    ...FONT,
    "--vscode-foreground": "#292929",
    "--vscode-descriptionForeground": "#292929",
    "--vscode-errorForeground": "#b5200d",
    "--vscode-focusBorder": "#006bbd",
    "--vscode-icon-foreground": "#292929",
    "--vscode-textLink-foreground": "#0f4a85",
    "--vscode-badge-background": "#0f4a85",
    "--vscode-badge-foreground": "#ffffff",
    "--vscode-button-background": "#0f4a85",
    "--vscode-button-border": "#0f4a85",
    "--vscode-button-foreground": "#ffffff",
    "--vscode-button-secondaryBackground": "#ffffff",
    "--vscode-button-secondaryForeground": "#292929",
    "--vscode-charts-blue": "#1a85ff",
    "--vscode-charts-green": "#388a34",
    "--vscode-charts-purple": "#652d90",
    "--vscode-charts-red": "#b5200d",
    "--vscode-charts-yellow": "#895503",
    "--vscode-checkbox-background": "#ffffff",
    "--vscode-checkbox-border": "#0f4a85",
    "--vscode-dropdown-background": "#ffffff",
    "--vscode-dropdown-border": "#0f4a85",
    "--vscode-dropdown-foreground": "#292929",
    "--vscode-editor-background": "#ffffff",
    "--vscode-editor-foreground": "#292929",
    "--vscode-editor-selectionBackground": "#0f4a85",
    "--vscode-editorCursor-foreground": "#0f4a85",
    "--vscode-editorIndentGuide-background": "#292929",
    "--vscode-editorLineNumber-foreground": "#292929",
    "--vscode-editorLineNumber-activeForeground": "#006bbd",
    "--vscode-editorWarning-foreground": "#895503",
    "--vscode-editorWidget-background": "#ffffff",
    "--vscode-editorWidget-border": "#0f4a85",
    "--vscode-editorWidget-foreground": "#292929",
    "--vscode-gitDecoration-conflictingResourceForeground": "#ad0707",
    "--vscode-gitDecoration-ignoredResourceForeground": "#8e8e90",
    "--vscode-gitDecoration-modifiedResourceForeground": "#895503",
    "--vscode-gitDecoration-untrackedResourceForeground": "#374e06",
    "--vscode-inputOption-activeBorder": "#0f4a85",
    "--vscode-inputOption-activeForeground": "#292929",
    "--vscode-panel-border": "#0f4a85",
    "--vscode-scrollbarSlider-background": "rgba(15, 74, 133, 0.4)",
    "--vscode-scrollbarSlider-hoverBackground": "rgba(15, 74, 133, 0.8)",
    "--vscode-scrollbarSlider-activeBackground": "#0f4a85",
    "--vscode-sideBar-background": "#ffffff",
    "--vscode-statusBarItem-warningBackground": "#895503",
    "--vscode-statusBarItem-warningForeground": "#ffffff",
    "--vscode-widget-border": "#0f4a85",
  },
};

/** The inline style VS Code would put on the webview body. */
export function bodyStyle(theme: VsCodeTheme): string {
  return Object.entries(VSCODE_THEMES[theme])
    .map(([k, v]) => `${k}:${v.replace(/"/g, "&quot;")}`)
    .join(";");
}
